plugins {
    id 'java'
}

group = 'com.slyph'
version = '1.13.0'

repositories {
    mavenCentral()
    maven {
        name = 'papermc'
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
    maven {
        name = 'placeholderapi'
        url = 'https://repo.extendedclip.com/releases/'
    }
    maven {
        name = 'jitpack'
        url = 'https://jitpack.io'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.110-stable'
    compileOnly 'me.clip:placeholderapi:2.12.3'
    compileOnly 'com.github.NEZNAMY:TAB-API:6.1.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

processResources {
    filesMatching('plugin.yml') {
        expand(version: project.version)
    }
}

jar {
    archiveBaseName = 'CloverBadges'
    archiveVersion = project.version
}
