name: CloverBadges
version: '${version}'
main: com.slyph.cloverbadges.CloverBadges
author: slyph
api-version: '1.16'
softdepend:
  - PlaceholderAPI
commands:
  badge:
    description: Управление бейджами CloverBadges
    usage: /badge
    aliases:
      - badges
      - cloverbadges
permissions:
  cloverbadges.*:
    default: op
    children:
      cloverbadges.use: true
      cloverbadges.menu: true
      cloverbadges.admin.*: true
  cloverbadges.admin.*:
    default: op
    children:
      cloverbadges.admin.give: true
      cloverbadges.admin.remove: true
      cloverbadges.admin.reload: true
  cloverbadges.use:
    default: true
  cloverbadges.menu:
    default: true
  cloverbadges.admin.give:
    default: op
  cloverbadges.admin.remove:
    default: op
  cloverbadges.admin.reload:
    default: op
